signal_assets: ["spy", "spyv", "ioo", "vtv", "qqq", "qqqe", "xlf", "xlk", "xle", "xly", "xlp", "tlt", "uso", "corp", "gld"]
target_assets: ["VIXY", "TQQQ"]
benchmark_asset: "SPY"

indicator: "RSI"
indicator_period: 10

signal_operator: ">="
threshold_start: 50.0
threshold_end: 80.0
threshold_step: 0.5

preconditions:
  - left: "benchmark_close"
    operator: ">"
    right: "benchmark_SMA_200"

date_range:
  start: "1950-01-01"
  end: "2026-03-15"